<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../TypeCobol/TypeCobol.csproj" />
  </ItemGroup>
</Project>

